#!/bin/bash
files=(
  "prisma/schema.prisma"
  "prisma/seed.ts"
  "src/app/(auth)/login/page.tsx"
  "src/app/(auth)/register/page.tsx"
  "src/app/(dashboard)/layout.tsx"
  "src/app/(dashboard)/dashboard/page.tsx"
  "src/app/(dashboard)/projects/page.tsx"
  "src/app/(dashboard)/projects/[id]/page.tsx"
  "src/app/(dashboard)/projects/[id]/costs/page.tsx"
  "src/app/(dashboard)/projects/[id]/categories/page.tsx"
  "src/app/(dashboard)/projects/[id]/vendors/page.tsx"
  "src/app/(dashboard)/projects/[id]/change-orders/page.tsx"
  "src/app/(dashboard)/projects/[id]/reports/page.tsx"
  "src/app/(dashboard)/settings/page.tsx"
  "src/app/api/auth/[...nextauth]/route.ts"
  "src/app/api/projects/route.ts"
  "src/app/api/projects/[id]/route.ts"
  "src/app/api/projects/[id]/summary/route.ts"
  "src/app/api/categories/route.ts"
  "src/app/api/costs/route.ts"
  "src/app/api/costs/[id]/route.ts"
  "src/app/api/costs/[id]/attachments/route.ts"
  "src/app/api/vendors/route.ts"
  "src/app/api/change-orders/route.ts"
  "src/app/api/reports/[id]/export/route.ts"
  "src/components/ui/Button.tsx"
  "src/components/ui/Card.tsx"
  "src/components/ui/Modal.tsx"
  "src/components/layout/Navbar.tsx"
  "src/components/layout/Sidebar.tsx"
  "src/components/dashboard/ProjectCard.tsx"
  "src/components/dashboard/BudgetSummaryCard.tsx"
  "src/components/costs/CostEntryForm.tsx"
  "src/components/costs/CostEntryTable.tsx"
  "src/components/reports/BudgetChart.tsx"
  "src/lib/db.ts"
  "src/lib/auth.ts"
  "src/lib/utils.ts"
  "src/lib/validators.ts"
  "src/hooks/useProjects.ts"
  "src/hooks/useCosts.ts"
  "src/types/index.ts"
  ".env.local"
  ".env.example"
)

for f in "${files[@]}"; do
  mkdir -p "$(dirname "$f")"
  touch "$f"
done

echo "Done. Created ${#files[@]} files."
